version: "3.9"

services:
  adminer:
    init: true
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "3215:8080"
    depends_on:
      - db
    networks:
      - polymathon

  back:
    init: true
    container_name: back
    ports:
      - "3000:3000"
    depends_on:
      - db
      - php
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

    build:
      context: ./project/back
    networks:
      - polymathon
    restart: unless-stopped

  php:
    init: true
    container_name: php
    build:
      context: ./project/wik
    networks:
      - polymathon
    restart: unless-stopped
    ports:
      - "8081:80"

  db:
    init: true
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - polymathon
    ports:
      - "5432:5432"
      
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind

networks:
  polymathon:
    driver: bridge
